// Development URLs
# http://localhost:3000
# http://localhost:3000/contacts
# http://localhost:3000/contacts/644402cbf75c6f2b4c479a4b
# http://localhost:3000/contacts/644402cbf75c6f2b4c479a4c
# http://localhost:3000/contacts/644402cbf75c6f2b4c479a4d


//Production URLs
# https://cprinceccse341.onrender.com/
# https://cprinceccse341.onrender.com/contacts
# https://cprinceccse341.onrender.com/contacts/644402cbf75c6f2b4c479a4b
# https://cprinceccse341.onrender.com/contacts/644402cbf75c6f2b4c479a4c
# https://cprinceccse341.onrender.com/contacts/644402cbf75c6f2b4c479a4d
